export const cards = [
    'Read a book',
    'Bubble bath',
    'Shower',
    'Leisurely walk',
    'Go into nature',
    'Take a nap',
    'Go out to dinner',
    'Watch the clouds float by',
    'Dance party',
    'Look at the stars',
    'Take nedication',
    'Arts & Crafts',
    'Go to a coffee shop',
    'Do yoga',
    'Medidate',
];
